### ISSUE TITLE
Thread ‘main’ panicked at ‘attempt to subtract with overflow’

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#1]
Entering `0` to go back (because that's what I learned from `gild`), this is what I get:

```
thread 'main' panicked at 'attempt to subtract with overflow', src/menu.rs:556:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Setting the suggested environment variable doesn't add any information, just 24 lines with

```
N: <unknown>
```

where `N` is in the interval 0..23.

**Comment by xvxx** [comment]
Whoops sorry, I have always been bad at maths... 

It should be fixed now in 7119c5f6061b89382ca1d0d15cf65d7ef447d075, I'll push a new release soon. Thank you for trying phetch!
