### ISSUE TITLE
Help (`-h`) seems to have too many TABs

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#10]
Some of the lines from `phetch --help` seem to have too many TABs:

![help](https://user-images.githubusercontent.com/25586/71926730-402f8b80-3194-11ea-8812-3015d0206217.png)

Seen in 032c10d6ec38285e2657ab08599cc5983b39ec04.

**Comment by xvxx** [comment]
That's what I get for trying to change sides in the "tabs vs spaces" war... I have switched back to the safety and comfort of manual padding with spaces: f90f4aef7ef83fc1a1eb234fbc77e67f7fc5bd0b Thank you!
