### ISSUE TITLE
Panic when truncating lines mid code point

### ISSUE THREAD

**Issue by ghost** [xvxx/phetch#13]
Good example of this is seen by visiting: `baud.baby`. You'll get a panic claiming byte index 'x' is not a char boundary.

The offending code is here: https://github.com/xvxx/phetch/blob/3791c9c64f2d0ffcab0d7a1dfa939cf8168c732b/src/menu.rs#L308

You're slicing a string without accounting for the index `MAX_COLS` possibly being in the middle of a code point. This is confirmed by the following replacement code which fixes the issue, instead truncating the line string using a char iterator:

```
let text_str = if line.text_len() > MAX_COLS {
    line.text(&self.raw).chars().take(MAX_COLS).collect::<String>()
} else {
    line.text(&self.raw).chars().collect::<String>()
};
let text = &text_str[..];
```

I'd have modified this and made a pull request myself, but I literally learnt Rust this afternoon for the purpose of fixing this panic, so I'm 95% sure there's a more elegant solution :stuck_out_tongue:

**Comment by xvxx** [comment]
Yikes, sorry about that! This was my "learn Rust" project so I'm sure there are more panics lurking around in the dark, when really I should have been passing around errors Go-style from the... get-go.

I'll push out a new release for this soon, there is maybe one other fix I want to get in there.

Thank you to @TheEnbyperor for fixing this so promptly!

PS `baud.baby` has probably the best header I've seen in Gopherland! Love the linework.
