### ISSUE TITLE
Feature request: open media files in media player

### ISSUE THREAD

**Issue by ghost** [xvxx/phetch#16]
Added beginnings of support for this in #15 

For whatever reason, ffmpeg supports opening gopher URLs. So `mpv gopher://some.url/9/file.mp4` actually will stream!

All we need to add is an action to open media files (item types `s` or `;`) with either mpv or VLC! Though the URL scheme supported for these is only item type `9`, so we'd need to replace the `s` or `;` item type in the URL with `9`

I'm already sharing my personal drive via gopher directory listing on my home network. With this change the combo of phetch + gopher server could make a very nice little media server :)

**Comment by xvxx** [comment]
Very cool! I added experimental support for this to the `master` branch under the `media` feature flag.

You can test it out by building like so:

    cargo build --features media

Or by running `cargo run` with the same flag.

Is `mpv` the only program that can do this? I've just hardcoded it in, but maybe there should be a config option eventually?

**Comment by ghost** [comment]
yes i've already tried and it's working great :D
https://twitter.com/grufwub/status/1264296292764856320

i'm pretty sure VLC supports this too, anything that relies on ffmpeg should do. So a user config setting for this would be a good idea :)

**Comment by xvxx** [comment]
Ha wow, that is awesome!

I also hacked in `URL:` support, so if someone wanted to collect their favorite YouTube gag videos (or public domain MP3s) in one place, they could do it the old fashioned way with a big Gopher menu:

    iMy Movies
    ;Great Cat Tips	URL:https://www.youtube.com/watch?v=dHw7O_cQ9KU
    ;The Big Question!	URL:https://www.youtube.com/watch?v=gW2QGYO5Ux0
    iMy Tunes
    sSoothing Sounds	URL:https://freepd.com/music/Beat%20Thee.mp3

I wasn't able to get VLC to play Gopher files so I'm going to just keep `mpv` as the default. In the future we can add a config option if people want to use different players.

**Comment by xvxx** [comment]
Okay, this is coming in the next release, complete with `-m`/`--media` flag to configure it. Thank you again!
