### ISSUE TITLE
Selector display not updating in terminal multiplexer

### ISSUE THREAD

**Issue by cyckl** [xvxx/phetch#17]
Hello, I seem to be running into an issue where if I have phetch running in a terminal multiplexer like [mtm](https://github.com/deadpixi/mtm), the screen doesn't update when I move around with the arrow keys. I can still browse to different pages normally, it's just that the selector doesn't accurately show the selected link.

I've tried running phetch with mtm in GNOME Terminal to no avail and I can sometimes get it to work in TTY.

Thanks.

Edit: I've tested phetch in tmux and it seems to work fine, maybe it's a problem with the multiplexer.

**Comment by xvxx** [comment]
Very interesting! Thank you for opening this issue. I think it might be a bug in the terminal library that phetch uses but I'm not sure. I've opened an issue on `mtm` to ask a few questions: https://github.com/deadpixi/mtm/issues/46

I've also "fixed" this in my fork of Termion, but I don't know if that's a sustainable solution, so hopefully someone can chime in on the `mtm` repo with some guidance: https://github.com/xvxx/termion/commit/bcfbf7c24050d26d05a6b0a16e0e58c1ab5f9fc5

As a workaround in the meantime, you can use `j`/`k` or `ctrl-n`/`ctrl-p` to move up and down. For going back and forward in history, you'll have to use the `ctrl-a` history viewer or just choose what sites you visit very carefully! Living on the edge, really.

I'll update this when there's a fix. Sorry about the bug!

**Comment by cyckl** [comment]
Thanks so much for replying quickly; I'll go ahead and monitor progress on both of these issues. As for the workarounds, I'll go ahead and employ those in the meantime. Much appreciated!

**Comment by cyckl** [comment]
Follow up: I've built phetch using your patched version of Termion, which fixed the issue for the most part, but I've run into another issue. With the new build, phetch and Termion's `keys.rs` example work right away in GNOME Terminal, but in TTY, I have to start another program like `htop` to get the arrow keys to work.

I can immediately use the `keys.rs` example without doing this but I have to do this for phetch. This means that the patched Termion is detecting the arrow keys fine, but phetch isn't. Any advice?

**Comment by xvxx** [comment]
When you say TTY, you mean the raw Linux console, right? Like `ctrl`+`alt`+`f3` in Ubuntu or booting into “console mode” on a Linux machine? It’s been a while since I used Linux full time, apologies! 

I have Pop!_OS (based on Ubuntu) and when I’m in TTY, phetch seems to work for me using the patched termion. Just to double check, this is what I put in the `Cargo.toml`:

```toml
[dependencies]
termion = { git = “https://github.com/xvxx/termion”, branch = “application-arrow-keys” }
```

When I make that change and build with `cargo run --no-default-features` (just because it’s faster), I get a version of phetch with working arrow keys in TTY. When I run it under `mtm`, the arrow keys work but phetch is black and white, no colors.

Any other hints you can give me about your environment so I can try to reproduce? Fully possible this is an unrelated bug just showing up here coincidentally, given the schrödinger-like nature of it.

**Comment by cyckl** [comment]
Yes, I’m using that TTY. Coincidentally, I’m also on Pop!_OS 20.04.

My ‘cargo.toml’ has the same setup except it’s linked to a local copy (folder is called `termion-patched`) of that repository and branch:

```toml
[dependencies]
termion = { termion-patched }
```

I’m using the default bash prompt, so maybe it has something to do with my install.

I’m going to try to set up a QEMU virtual machine and use that setup to see if it makes any difference, since it seems we have the same setup.

Thanks for your continued support!

**Comment by xvxx** [comment]
@cyckl The author of `mtm` updated it with a fix and now it's working great for me: https://github.com/deadpixi/mtm/commit/9b3b6be35e28fdac587b8973bf8719fe80f74195 

Can you try using the release version of `phetch` with the newest `mtm` and let me know if that works for you too? The Termion change might not be necessary.

**Comment by cyckl** [comment]
Yeah, I just updated and rebuilt everything and it works flawlessly; just without color. Thanks for the help!
