### ISSUE TITLE
Features update

### ISSUE THREAD

**Issue by ghost** [xvxx/phetch#18]
Hi,
I've just packaged `phetch` for NetBSD. The package is currently in the testing repo but its my goal to move it to the main one within a few days. 
Could you please update the README.md file adding NetBSD to the list of OS/plattform supporting `phetch`?
Thx!

**Comment by xvxx** [comment]
That is super awesome!

Can you share installation instructions, so I can add those to the README too? Or do NetBSD users just know how to install stuff so listing the platform is enough? I have not really used it in a while sorry!

**Comment by ghost** [comment]
My pleasure to make new software available to NetBSD users :)

If you have used NetBSD, you will know that there are several branches, both for the packaging system and the base OS, that you can combine/mix as it suites your needs.
Myself, I run the 9.0_STABLE base with pkgsrc-current but, there are other possible combinations.

Anyway, I'll move the package to the main repo today or tomorrow, I'm happy with the testing so far.
Doing so it will make the package available in the coming Q3 branch for the users that are running the stable pkgsrc branch.

There are two ways of installing packages on NetBSD, either through pre-compiled binaries using the package manager or, building from source with pkgsrc.

**Instructions**

**Using the package manager**
`# pkgin install phetch`

**Building from source**
Make sure you have `rust` installed and define the preferred `RUST_TYPE` in `/etc/mk.conf` before you run
```
$ cd /usr/pkgsrc/net/phetch
$ make
# make install
```
Optional: once done, clean the build directory.

**Comment by ghost** [comment]
@xvxx package `phetch` now in the main branch, https://mail-index.netbsd.org/pkgsrc-changes/2020/09/09/msg220684.html

Feel free to close this issue once the README is updated. Thanks for a nice tool to surf _gopher holes_.

**Comment by xvxx** [comment]
Excellent! Thank you so much!

I've added NetBSD to the list of platforms and included installation instructions in 053dcec7649e7bcab81eb5dcee3c3c5247ac3e7d
