### ISSUE TITLE
Enhancement: ‘q’ or ‘Esc’ to quit

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#2]
Please, can we have `q` (and possibly `Esc`) to quit? Right now I press `0` and `phetch` will exit qith a stack trac, as mentioned in #1, but `q` and `Esc` will feel more intuitive.

PS: I really like the navigation in `phetch`, it feels like a huge improvement compared to `gild`.

**Comment by kseistrup** [comment]
Oh, the first time I ran `phetch` I have it a gopher URL, so I didn't notice that there is a help page.

**Comment by xvxx** [comment]
> Please, can we have q (and possibly Esc) to quit?

Yes, great suggestion. You can now quit with `Esc`. If you've entered text in a search field or there's a message of some sort pending it'll first act as a "cancel " and clear the message/text. But if there's nothing pending, it'll quit. `ctrl-c` will work the same way, and`ctrl-q` will quit the app immediately.

> PS: I really like the navigation in phetch, it feels like a huge improvement compared to gild.

Great, thank you! Your ideas contributed a lot. 

> Oh, the first time I ran phetch I have it a gopher URL, so I didn't notice that there is a help page.

Ah yes, I think I would probably launch any new gopher app with a URL as well. Maybe I can flash a status message advertising `ctrl-h` on first launch or something.

**Comment by kseistrup** [comment]
> `ctrl-h`

Or you can add it as an epilog to the standard help text:

```
$ phetch --help
Usage
    phetch                           # Launch and show start page.
    phetch <gopher-url>              # Open Gopherhole at URL.
    phetch -r, --raw <gopher-url>    # Print raw Gopher response.
    phetch -h, --help                # Show this screen.
    phetch -v, --version             # Show phetch version.

Press ‘ctrl-h’ at any time during a session to go to the
builtin help page.
$ 
```

**Comment by kseistrup** [comment]
Oh, and btw: I really like that the builtin help pages are gopher pages. I had to check that I weren't at an external site. Looks very slick. :+1:

**Comment by xvxx** [comment]
> Or you can add it as an epilog to the standard help text:

Great, added! I'm pushing a new release soon.

> I really like that the builtin help pages are gopher pages.

Thanks! I thought it was a good fit, plus it kind of doubles as a sort of "sandbox" to play around with the app without hitting someone's innocent server too much.

**Comment by kseistrup** [comment]
Well done!
