### ISSUE TITLE
Scroll behavior

### ISSUE THREAD

**Issue by Poorchop** [xvxx/phetch#24]
Is it possible to add an option to scroll the entire height of the viewport/by page? Pressing spacebar or page down seems to only scroll by a fixed amount of lines, which requires taking time to figure out where I left off while reading a block of text. Scrolling an entire page makes it so that we can pick up from the top of the terminal after previously reading the last visible line.

**Comment by xvxx** [comment]
Good idea. I just added the `scroll` option in 68618482177fe407c3c07496251a0528e7b76a4b. It'll default to scrolling by an entire page now. It is a nicer experience, you're right. People can use `scroll 15` to return to the old behavior.

This change will appear in the next release. Thank you!

**Comment by Poorchop** [comment]
Thank you.
