### ISSUE TITLE
configure colours

### ISSUE THREAD

**Issue by pfr-dev** [xvxx/phetch#25]
I use a light theme and, while i have my yellow set in `.Xresources` to be darker than usual, Phetch uses a lot of yellow text. It would be nice to be able to configure the colours in a simple config file.

**Comment by pfr-dev** [comment]
I just thought I'd let you know that _(if you ever come back from your fishing trip)_ I've forked `phetch` purely so I can change the hardcoded colours in the `color.rs`

I'm not really skilled enough to do much else, so if you ever return and decide to pick this up again please can you allow for customising colours in the config file? 
Cheers.

**Comment by xvxx** [comment]
@pfr-dev I have returned and I'll try to include this in the next update. Thank you for opening the issue!

**Comment by xvxx** [comment]
Added in 8ebeb8dec9c30e59d0eec019969f1d43167daab5, color themes will be in the next release:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/41523880/201581003-63bbf5f0-0c2b-41a6-a837-1bdb1fbb239a.png">

**Comment by xvxx** [comment]
This is now included in the [1.2.0](https://github.com/xvxx/phetch/releases/tag/v1.2.0) release, thank you!
