### ISSUE TITLE
Resuming from ^Z breaks drawing

### ISSUE THREAD

**Issue by ghost** [xvxx/phetch#27]
When I use ^Z to suspend phetch and then resume it, keystrokes render on the screen and phetch doesn't update the screen to reflect said keystrokes.

**Comment by xvxx** [comment]
@anahata0108 Thanks for opening an issue! Which terminal/shell/OS combination are you using?

**Comment by ghost** [comment]
This occurs with iTerm2 and Konsole using zsh, bash, dash, and tcsh on Linux, macOS, and FreeBSD with the terminal types tmux-256color, xterm-256color, and xterm. In short, it occurs in every configuration I have access to.

**Comment by xvxx** [comment]
Strangely it works fine with `fish` which is why I didn't notice, but you're right that it's broken basically everywhere else.

Just pushed fb1b3d218560768aec5e0a95fa83970e40037d9c which fixes it. Thank you for reporting!
