### ISSUE TITLE
Circular navigation

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#4]
How do you like the idea of “circular navigation”? We can use the front page as an example:

![phetch](https://user-images.githubusercontent.com/25586/71508071-e91de280-2886-11ea-8882-7b335417e9ff.png)

And let's pretend that we can only navigate by numbers or cursor keys. If I want to select **7**, I either have to move my hand to the `7` button or I have to press cursor down 6 times.

What if moving off the top took me to the bottom, and moving off the bottom took me to the top, as if the numbers were placed on a ring?

I.e., when I want to move from **1** to **7**, I can simply press **↑** once and I get to keep my fingers on the arrow keys.

**Comment by xvxx** [comment]
Ohhh, I love it! Things are much more fluid now. 💧 

I am pushing out `0.1.4` with this change! Thank you as always!

**Comment by kseistrup** [comment]
Thank _you_!
