### ISSUE TITLE
Found the missing Makefile 😉

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#5]
I felt a `Makefile` was missing, so I wrote one. I rarely write makefiles, so you can most likely do a much better job yourself, but here's a simple one:

:paperclip: [Makefile](https://github.com/dvkt/phetch/files/4009645/Makefile.txt)

**Comment by xvxx** [comment]
I've been looking for that!! Thank you! Added in b19b5e592d00016d34ac7ae8074ab35a7d443fd5
