### ISSUE TITLE
--raw: erratic behaviour

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#7]
Seen in f533d15ac25f381138f4be94d9288e06b3bf9ea3:

It seems like `phetch` is ignoring its first argument after `--raw`:

```sh
$ phetch --raw phkt.io
--raw needs gopher-url
$ phetch --raw IGNORED phkt.io | head -1
i  ____    _   _     _  __    _____	(null)	phkt.io	70
$ phetch --version
phetch v0.1.12-dev
```

**Comment by xvxx** [comment]
Whoops, thank you! This will be fixed in the next release.
