### ISSUE TITLE
Cargo.toml: no feature ‘tls’

### ISSUE THREAD

**Issue by kseistrup** [xvxx/phetch#8]
Seen in b07252997b5e29367ea646c6364207d90e0a3cc0:

```sh
$ make
cargo build --release --features tls
error: Package `phetch v0.1.12-dev (…/phetch)` does not have these features: `tls`
make: *** [Makefile:22: target/release/phetch] Error 101
```

Omitting `--features tls` from `Makefile` builds the intended target since it is now the default.

**Comment by xvxx** [comment]
I originally went too conservative and made it so you had to *enable* TLS when building, but this morning I switched it so you need to explicitly *disable* TLS. That's what this error is from, I missed the Makefile when doing the switch.

I just pushed a fix for this, and the README now has the up-to-date information under the "development" section:

     cargo build --features disable-tls

Thanks again!
